name: rarui
description: "RarUI Design System"
version: 0.0.2
homepage: "https://github.com/rarolabs/mobile-rarui"
repository: "https://github.com/rarolabs/mobile-rarui"
issue_tracker: "https://github.com/rarolabs/mobile-rarui/issues"

environment:
  sdk: ^3.6.0

dependency_resolution:
  resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  br_validators: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  
flutter:
  uses-material-design: true
