name: rarUI
description: "RarUI"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependency_resolution:
  resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner_plus: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  
flutter:
  uses-material-design: true
