name: rarUI
description: "RarUI Theme"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependency_resolution:
  resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  auto_size_text_plus: 3.0.2
  currency_text_input_formatter: 2.2.6
  diacritic: 0.1.6
  flutter_svg: 2.0.16
  intl: 0.19.0
  pinput: 5.0.0
  shimmer: 3.0.0
  camera: 0.10.6
  clean_calendar:
    git:
      url: git@git.rarolabs.com.br:qesh/clean_calendar_fork.git
      ref: master

  mime: 2.0.0
  flutter_styled_toast: 2.2.1
  screenshot: 3.0.0
  qr_flutter: 4.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
